### ISSUE TITLE
Matching <'list-style'> incorrectly due to <custom-ident>

### ISSUE THREAD

**Issue by lmgonzalves** [csstree/csstree#101]
First of all, great work here! Thanks!

I'm having an issue matching the property `<'list-style'>` with value `inside`.
The token `inside` should be matched as `<'list-style-position'>`, but it is matched as `<'list-style-type'>` instead. See:

![list-style](https://user-images.githubusercontent.com/12473993/60897175-9cd9da00-a235-11e9-8001-eea1626c6556.png)

This happens because `<'list-style-type'>` could be a `<custom-ident>`, so it will match the `<'list-style-position'>` tokens too (`inside` | `outside`).

I think this is related with #85, and may affect any other syntax containing `<custom-ident>`, if it takes priority over other tokens.

Thanks again for this great library!

**Comment by lahmatiy** [comment]
Thank you for your feedback!

About the case. That’s not #85 related, since #85 is about matching order. In case of `<custom-ident>`, an issue about priority. There is [a rule](https://www.w3.org/TR/css-values-3/#custom-idents) in CSS Values and Units I missed before:
> When parsing positionally-ambiguous keywords in a property value, a `<custom-ident>` production can only claim the keyword if no other unfulfilled production can claim it.

That’s on my TODO list for next release (will be available later today or yesterday)

**Comment by lmgonzalves** [comment]
Awesome! Thanks!
Please feel free to close it when appropriate.

**Comment by lahmatiy** [comment]
In upcoming version:
![image](https://user-images.githubusercontent.com/270491/61014176-d2460b00-a38e-11e9-9c05-407582e3368a.png)

**Comment by lahmatiy** [comment]
`1.0.0-alpha.31` is out, see [release notes](https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha.31) for details
