### ISSUE TITLE
'debugger' in source code

### ISSUE THREAD

**Issue by steida** [csstree/csstree#104]
I suppose it's a bug.

https://github.com/csstree/csstree/blob/565a464448f2932c45ec85e8d16170a68fc1c5c6/lib/lexer/generic.js#L399

**Comment by lahmatiy** [comment]
You're right, I'll fix it. Thank you!

**Comment by steida** [comment]
It must be a pain to develop this wonderfull library without TypeScript. Thank you for all your work!
