### ISSUE TITLE
Infinite loops

### ISSUE THREAD

**Issue by tbjgolden** [csstree/csstree#107]
I've been trying to analyse large amounts of CSS recently but found that csstree doesn't always finish parsing with unusual, corrupted inputs, or even terminate

In particular, I've been using the massive CSS file found in this zip: https://www.kaggle.com/zavadskyy/lots-of-code

As the file is too large to parse in a single iteration, I had to split it into chunks to parse it (and just accepting it will be lossy) and just split it into strings that I parse one after the other, which worked

However, sometimes parsing would end up in an infinite loop on some of the chunks and stop the whole process.

Is there a way for the csstree algorithm to be able to detect infinite recursion and throw an error?

The areas in the css.txt file in that zip that caused issues were:

- a massive css comment with 60,000 characters
- anything corrupted looking data with a bunch of unusual characters, potentially badly encoded (think chars like `¾` in there etc)

any extra info or questions just lmk :D

**Comment by tbjgolden** [comment]
Okay so I ran a regex over my source css:
`.replace(/[^\x09\x0A -~]+/g, '')`

and no more infinite loops

seems the parse function would break on `\x00` null chars, and maybe also some non ascii characters

Would it therefore make sense to throw an Error on seeing one of these characters in the source, or maybe just to skip over them?

**Comment by tbjgolden** [comment]
Also for anyone that comes upon something like this, I just passed the css through this:

```
/* eslint-disable no-control-regex */

const fs = require('fs-extra');
const path = require('path');

fs.writeFile(
  path.join(__dirname, 'ascii.css.txt'),
  `${fs.readFileSync(path.join(__dirname, 'css.txt'))}`.replace(/[^\x09\x0A -~]+/g, '')
);

```

will prevent this happening

**Comment by lahmatiy** [comment]
It can be a problem to parse CSS file greater than 16Mb (2^24 bytes), because at the moment some optimisations is used. Probably we need to throw an exception when size limit exceeded or change implementation to handle such huge amount of CSS.

I can't reproduce your case. Can you produce a chunk where an infinite loop occurs?

> Would it therefore make sense to throw an Error on seeing one of these characters in the source, or maybe just to skip over them?

I believe it should be parsed. However, some bugs may take place. But I need a test case to find a problem.

**Comment by lahmatiy** [comment]
I used the following code to test your hypothesis:

```js
let x = '';

for (let i = 0; i < 65536; i++) {
    x += String.fromCharCode(i);
}

csstree.parse(x);
```
No infinite loop, parsed as expected.

**Comment by tbjgolden** [comment]
Closing issue as the explanation with the 2^24 explained what was happening
