### ISSUE TITLE
Unknown property `font-display`

### ISSUE THREAD

**Issue by sayemon10** [csstree/csstree#108]
please ADD font-display: swap in the system

**Comment by sayemon10** [comment]
![image](https://user-images.githubusercontent.com/35277447/64328446-439ce580-cfef-11e9-882f-d06101e3415b.png)

**Comment by lahmatiy** [comment]
`font-display` is a descriptor. Unfortunately, `css-tree` doesn't support for descriptor's validation currently (see #49)
Duplicates #48
