### ISSUE TITLE
Add a node type "None"

### ISSUE THREAD

**Issue by fstanis** [csstree/csstree#113]
I was looking for an easy way to remove nodes that match a certain blacklist, for example media queries that use the `color` feature.

To do this, I traverse the tree and when I find a `MediaFeature` that matches a blacklisted one, I want to remove the `atrule` from the context.

```js
csstree.walk(ast, function(node) {
  if (node.type === 'MediaFeature' && node.name === 'color') {
    this.atrule.type = 'Raw';
    this.atrule.value = '';
  }
});
```

It occurred to me this is quite a hacky way to do things. I was wondering if we could perhaps add a special node type `None` that'd simply mean "ignore this node and all of its properties / children"?

**Comment by lahmatiy** [comment]
Hi! If you need to remove a node, just remove it on traversal:

```js
function isColorMediaFeature(node) {
    return node.type === 'MediaFeature' && csstree.keyword(node.name).name === 'color';
}

csstree.walk(ast, {
    visit: 'Atrule',
    enter(node, item, list) {
        if (node.name.basename === 'media' && csstree.find(node.prelude, isColorMediaFeature)) {
            list.remove(item);
        }
    }
});
```

**Comment by fstanis** [comment]
Hm, that works, but wouldn't marking nodes as removed (`'None'`) be more efficient than calling `list.remove`?

Assuming of course we also add logic that e.g. ignores `children` in traversal when `node.type` is `None`.

**Comment by lazarljubenovic** [comment]
What's the point of keeping a removed node in the tree, though? If you have a use-case where you temporarily want to mark something as removed, you could create a set where you keep the removed nodes, and then skip over this that belong to the set during traversal. Sets are implemented as hash tables in v8, so it's O(1) in practice to check.

**Comment by fstanis** [comment]
Oh, I don't have a need for keeping the node, I just want it not to exist as output in `csstree.generate`.

It seems faster to mark it as removed (constant time) for these purposes than to use `list.remove` (which is presumably linear time). This is probably premature optimization, but I still see value in a `None` type for these purposes.

**Comment by lahmatiy** [comment]
A `list` in a walker handler (which is used for `children`) is a bi-directional list. So `list.remove()` has nearly constant time because it turns to a few reference updates ([implementation](https://github.com/csstree/csstree/blob/master/lib/common/List.js#L409)).

**Comment by lahmatiy** [comment]
Btw, you can alter generator behavior using `decorator` option. All you need is to mark desired nodes somehow and override `node` handler, which do nothing when node is marked or invoke default node handler otherwise.
You also can add a new node type using `fork()` (see example [here](https://github.com/csstree/stylelint-validator/blob/master/index.js#L2)). However it looks like overkill in this case.

**Comment by fstanis** [comment]
Ah, right, forgot it's a bi-directional list. Yep, no speed gains whatsoever then.

Altering generator behavior also seems like overkill since the `Raw` solution from my first post technicall works - but after this explanation, it seems completely unneccessary to ever use.

Thanks for being patient and explaining everything!
