### ISSUE TITLE
Parse error: RightParenthesis is expected

### ISSUE THREAD

**Issue by Mrwaite** [csstree/csstree#115]
my css file content is

> .a{
filter: alpha(opacity=0);
}

after `csstree.parse`, throw error

> Parse error: RightParenthesis is expected
    1 |.a{
    2 |filter: alpha(opacity=0);

**Comment by lahmatiy** [comment]
What version do you use?
`alpha(opacity=0)` is legacy IE syntax and can’t be parsed by standard parse rules. However, csstree is tolerant to errors, so it wraps bad content (like in your case) in `Raw` nodes and doesn’t raise an errors. I suppose you’re using one of old versions without tolerant parsing.

**Comment by Mrwaite** [comment]
thanks, you reply me in time.
css-tree version is 1.0.0-alpha.39 which i use. but i think css-tree should consider the compatibility of legacy IE syntax. and css-tree can continue to parse instead of interrupting parsing.

**Comment by lahmatiy** [comment]
> css-tree can continue to parse instead of interrupting parsing

It does: https://observablehq.com/@lahmatiy/css-tree-issue-115. I have no idea why you get an error. Make sure you use latest version or [alpha.26+](https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha.26). If you don't pin a version in dependencies (i.e. without any `^` or `~`), some old version can be installed instead expected version. Or provide your code where you're use `csstree.parse()`, so I can investigate the issue.

> css-tree should consider the compatibility of legacy IE syntax

I believe, it should not. But you can extend parser and the rest to support any hacks and legacy, see details here: https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha17

**Comment by williamyeny** [comment]
Is there any update on how to fix this? Our customers' CSS files have legacy syntax that they can't remove.
