### ISSUE TITLE
Office- and Outlook-proprietary CSS attributes

### ISSUE THREAD

**Issue by revelt** [csstree/csstree#116]
CSS is being used not only in _web page development_ but also in _email template development_. In latter, the lowest denominator which decides the style of coding is Microsoft Outlook. Outlook uses MS Word rendering engine which can be compared to IE5, that's why email templates are coded in tables.

Email developers found a way to cater the Outlook deficiencies — by using mso-proprietary CSS attributes. For example, perfectly correct template might use `mso-table-lspace:0;mso-table-rspace:0;`.

There are at least 374 proprietary `mso-` attributes, see unofficial list [here](https://stigmortenmyre.no/mso/html/concepts/ofconstyletable.htm).

CSSTree is a universal tool but but until it supports `mso-` proprietary attributes it can't be used in email-related tooling. Theoretically, the `mso-` attributes should be somehow added onto CSSTree "out-of-the-box", or there should be a way to CSSTree consumers to supplement these ad-hoc, via options (Whitelist array at least? But then how about value validation?).

At minimum CSSTree validator should skip `mso-` attributes, ideally it should fully parse and validate their types.

What do you think?

**Comment by lahmatiy** [comment]
You can use your own dictionary with CSSTree or extend existed, by using `fork()` method:
```js
const csstree = require('./lib'); // default syntax

console.log(csstree.lexer.matchProperty('mso-background', 'red'));
// {
//    matched: null,
//    iterations: undefined,
//    error: SyntaxError [SyntaxReferenceError]: Unknown property `mso-background`
//    ...

const mySyntax = csstree.fork({
    properties: {
        // add/override properties
        'mso-background': 'auto | <color> | windowtext'
    },
    types: {
        // ... or types
    }
});

console.log(mySyntax.lexer.matchProperty('mso-background', 'red'));
// {
//    matched: {
//      syntax: { type: 'Property', name: 'mso-background' },
//      match: [ [Object] ]
//    },
//    iterations: 22,
//    error: null,
//    ...
// }
```

**Comment by revelt** [comment]
thanks a lot! Closing.
