### ISSUE TITLE
cssTree.generate is not a function

### ISSUE THREAD

**Issue by mikevoets** [csstree/csstree#119]
**Version**: css-tree: 1.0.0-alpha.39; @types/css-tree: 1.0.3

The `csstree.generate` doesn't seem to be working anymore. When I try to run it, I get the following error:

`TypeError: cssTree.generate is not a function`

I had to downgrade css-tree to 1.0.0-alpha.34 and @types/css-tree to 1.0.1 as a workaround.

**Comment by Detruire** [comment]
I have recently updated to alpha.39 without encountering this problem.

Do you still receive that error with a stripped down project like the following? This example compiles without error and runs as expected for me.

_index.ts:_
```typescript
import * as cssTree from 'css-tree'

const ast = cssTree.parse('div.test { color: red; }')

console.log(cssTree.generate(ast))
```
_package.json:_
```json
{
  "name": "css-tree-test",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "tsc --noEmit index.ts"
  },
  "author": "",
  "license": "unlicensed",
  "private": true,
  "devDependencies": {
    "@types/css-tree": "^1.0.3",
    "typescript": "^3.8.2"
  },
  "dependencies": {
    "css-tree": "^1.0.0-alpha.39"
  }
}
```

**Comment by lahmatiy** [comment]
`generate()` method did not changed since 1.0.0-alpha.27.
Make sure you pin `css-tree` version and correct version is installed. When `^` is used, npm may install wrong version (e.g. 1.0.0-alpha19). Installed version may be checked by `npm ls css-tree` command.
