### ISSUE TITLE
stroke-dasharray 

### ISSUE THREAD

**Issue by gwer** [csstree/csstree#12]
![2016-09-13 11 41 50](https://cloud.githubusercontent.com/assets/6529684/18467085/2ec1ed6e-79a7-11e6-8ca4-13f22ffdeef9.png)
Должно принимать значение _none | &lt;dasharray&gt; | inherit_, где &lt;dasharray&gt; — «It's a list of comma and/or white space separated &lt;length&gt;s and &lt;percentage&gt;s that specify the lengths of alternating dashes and gaps».

**Comment by lahmatiy** [comment]
`<length-percentage>#` is actually `a list of comma and/or white space separated <length>s and <percentage>s`. But I guess for SVG properties length unit can be omitted (see #6).
