### ISSUE TITLE
what "atrule" option is unclear

### ISSUE THREAD

**Issue by jacobbogers** [csstree/csstree#120]
from the docs in your readme https://github.com/csstree/csstree/blob/master/docs/parsing.md#atrule
```bash
atrule
Type: string or null
Default: null

Using for atrulePrelude context to apply atrule specific parse rules.
```
What would the string be and how would it be used to apply specific parse rules?

**Comment by lahmatiy** [comment]
It should be at-rule name (lowercase with no vendor prefix). Available specific parse rules are defined at https://github.com/csstree/csstree/blob/master/lib/syntax/atrule/index.js. However, if you specify a value that is not in the list, the default parsing rules will be applied.
Specific at-rules parse rules can be extended or redefined by `csstree.fork()` method.
