### ISSUE TITLE
Consider previos CSS sourse map

### ISSUE THREAD

**Issue by constgen** [csstree/csstree#122]
Lets say I need to write a Webpack loader that is somewhere in the middle of styles loaders pipe. It is going to process the output result with pure CSS and source maps from another loader (e.g. Less or SASS) . So is it possible to transform CSS considering previous source maps?

**laoder.js**

```js
let csstree = require('css-tree');

module.exports = function (source, sourceMap) {
	let filename = this.resourcePath;
	let ast = csstree.parse(source, {
		filename,
		positions: true
	});

	csstree.walk(ast, { /* some transforms */});

	let { css, map } = csstree.generate(ast, { sourceMap: true });
	let newMergedSourceMap = '???' // <- this is what the question about

	this.callback(null, css, newMergedSourceMap );
};
```

So I am looking how to "merge" `sourceMap` and `map.toJSON()` to a single final source map

**Comment by lydell** [comment]
This function can merge source maps: https://github.com/mozilla/source-map#sourcemapgeneratorprototypeapplysourcemapsourcemapconsumer-sourcefile-sourcemappath

**Comment by lahmatiy** [comment]
@constgen Take a look how csso-cli performs source maps merge: https://github.com/css/csso-cli/blob/master/index.js#L302

**Comment by constgen** [comment]
Thanks. I think I have the answer. As soon I implement this successfully I will close the issue.

**Comment by constgen** [comment]
I will leave here the answer to my own question for those who will search in the future. Considering the new async API of Source Map package the solution approximately should look like this (the code is simplified)

```js
let csstree = require('css-tree')
let { SourceMapConsumer } = require('source-map')

module.exports = function styleLoader (source, sourceMap) {
	let filename = this.resourcePath
	let ast = csstree.parse(source, {
		filename: toUnixPath(filename),
		positions: true
	})
	let callback = this.async()
	csstree.walk(ast, { /* some transforms */});
	new SourceMapConsumer(sourceMap)
		.then(mapConsumer => {
			let {css, map}= csstree.generate(ast, {sourceMap: true})
			map.applySourceMap(mapConsumer, toUnixPath(filename))
			map = map.toJSON()
			mapConsumer.destroy()
			return { css, map }
		})
		.then(({ css, map }) => callback(null, css, map))
		.catch(err => callback(err))
}
```
