### ISSUE TITLE
ES5/IE11 support?

### ISSUE THREAD

**Issue by strarsis** [csstree/csstree#137]
For ES5/IE11 support the `const` keyword must be replaced with `var`. Are there any ways to transpile this?

**Comment by lazarljubenovic** [comment]
Use a transpiler like babel?

**Comment by lahmatiy** [comment]
CSSTree primary target is Nodejs which supports ES6+ for many years. Generally, support for browser's bundle is a "nice to have" feature which provided for experiments and using with modern browsers only. When CSSTree is a dependency of an app/lib I believe their authors already used some kind of bundling which can perform a transpilation to ES5 or any other versions of ECMA script depending on project's requirements. Adding a transpilation to CSSTree project brings undesired growth in dev deps count, complexity and package size. Given that the need for ES5 support is extremely small these days, I don't think it's worth it.
Closing the issue as `won't fix`.
