### ISSUE TITLE
Parse error: Unexpected input 

### ISSUE THREAD

**Issue by GitScrum** [csstree/csstree#14]
> Parse error: Unexpected input 
> 194 | font-size:.846em; 
> 195 | text-shadow:0 -1px #000; 
> 196 | filter:dropshadow(color=#000,offx=0,offy=-1); 
> -------------------------------^ 
> 197 | color:#fff; 
> 198 | border:.091em solid #3e3e3e;

**Comment by GreLI** [comment]
FYI: list of old IE filters: https://msdn.microsoft.com/en-us/library/ms532853(v=vs.85).aspx

**Comment by lahmatiy** [comment]
@GreLI Yep, I saw it. But that page better https://msdn.microsoft.com/en-us/library/ms532847(v=vs.85).aspx - see `Filters Mapping` table in the middle.
But I'm not sure all of those filters are used by someone.
