### ISSUE TITLE
 1.1.0 update error: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by kelf477** [csstree/csstree#144]
I'm getting the following error with the new 1.1.0 update on my NativeScript project:

System.err: TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5954)
System.err:     at android.app.ActivityThread.access$1200(ActivityThread.java:200)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:201)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6810)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
System.err: Caused by: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
System.err: File: (file: node_modules/css-tree/lib/syntax/config/mix.js:140:0)

**Comment by lahmatiy** [comment]
Data is not enough to understand what problem is and how to fix it.
Did it work before 1.1.0? Is it any suggestions why it's broken?
According to stack trace `mix.js:140:0` is about `module.exports = ...`, this assignment was before, only function was changed to arrow function.

**Comment by lahmatiy** [comment]
Closing the issue since no more details provided and no more reports about the problem.
