### ISSUE TITLE
version >=1.1.0 has broken in node 8

### ISSUE THREAD

**Issue by zoobestik** [csstree/csstree#145]
It happened after refactor mix - [lib/syntax/config/mix.js#L23](https://github.com/csstree/csstree/blob/v1.1.0/lib/syntax/config/mix.js#L23)
But it's [`"node": ">=8.0.0"`](https://github.com/csstree/csstree/blob/v1.1.0/package.json#L53)
Example log with usage in [csso-webpack-plugin](https://travis-ci.org/github/zoobestik/csso-webpack-plugin/jobs/745144818)

**Comment by lahmatiy** [comment]
That's interesting, spread operator in object literals was added in `8.3` (according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)).
Not sure we need to fix it. But I'll rollback it for 1.x

**Comment by lahmatiy** [comment]
Fixed in 1.1.2
