### ISSUE TITLE
List documentation missing

### ISSUE THREAD

**Issue by maximilianMairinger** [csstree/csstree#146]
At https://github.com/csstree/csstree/blob/master/docs/ast.md

> NOTE: The example uses arrays for the values of the property children. In fact, the values of this property are instances of the [List](https://github.com/csstree/csstree/blob/master/docs/List.md) class.

https://github.com/csstree/csstree/blob/master/docs/List.md is not found

**Comment by matthewmueller** [comment]
+1. The AST grammar is super useful, but left wondering what the List interface represents.

**Comment by lahmatiy** [comment]
[List documentation](https://github.com/csstree/csstree/blob/master/docs/list.md)
