### ISSUE TITLE
[Question] How can I collect the full selectors for each rule?

### ISSUE THREAD

**Issue by npearson72** [csstree/csstree#147]
I'm new at this, so please forgive me if this is naive. But I'm trying to get the full selectors that I can test against my HTML to only use the CSS that's needed.

This is what I'm doing so far:

```
const ast = csstree.parse(`
  button#primary.red, button#primary.orange { color: "red" }
  div#logo { height: "100px" }
`);

selectors = [];
const collector = (node, current) => {
  if (node.data.type === 'TypeSelector') current = current + node.data.name;
  if (node.data.type === 'IdSelector') current = current + `#${node.data.name}`;
  if (node.data.type === 'ClassSelector')
    current = current + `.${node.data.name}`;

  if (!node.next) return selectors.push(current);

  if (node.next) collector(node.next, current);
};

csstree.walk(ast, node => {
  if (node.type === 'Selector') {
    collector(node.children.head, '');
  }
});

console.log(selectors); // [ 'button#primary.red', 'button#primary.orange', 'div#logo' ]
```

But I'm wondering if this is the best way or if there's a more clever trick to this?

Also, please forgive me if this isn't the best forum for questions. I didn't see anything in the README about a Gitter or Slack channel.

**Comment by lahmatiy** [comment]
Your solution to find selectors is fine. But you need to use [`generate()`](https://github.com/csstree/csstree/blob/master/docs/generate.md) method to get a string representation of the selector. So code will be much simpler:

```js
const { walk, generate } = require('css-tree');
const selectors = [];

walk(ast, {
    visit: 'Selector',
    enter(node) {
        selectors.push(generate(node));
    }
});

console.log(selectors);
```

**Comment by npearson72** [comment]
Thanks!
