### ISSUE TITLE
Url("data:...") - quotes removed during parse

### ISSUE THREAD

**Issue by pmatisko** [csstree/csstree#177]
Hello!

Is this behavior a bug, or I am doing something wrong?  Replication should be easy.

```
myClass: {
background-image: url("data: data:image/svg+xml .... ");
}
```

Then run:

```
const cssAST = csstree.parse(css)
const cssPlain = csstree.toPlainObject(cssAST)
const finalCSS = csstree.generate(cssPlain)
```

finalCSS will not have the quotes in the resulting url which is a problem in Vue.  The result will look like this:

```
myClass: {
background-image: url(data: data:image/svg+xml .... );
}
```

**Comment by lahmatiy** [comment]
@pmatisko Removing quotes is correct from CSS spec perspective. CSSTree encodes url's value so it should work in any browser. Currently there are no options to setup using quotes for `url()`, but you can change serialization this way:

```js
const alteredCsstree = csstree.fork({
    node: {
        Url: {
            generate(node) {
                this.token(TYPE.Url, csstree.string.encode(node.value));
            }
        }
    }
});

// use alteredCsstree instead of csstree
const cssAST = alteredCsstree.parse(css)
// ...
const finalCSS = alteredCsstree.generate(cssAST)
```

**Comment by pmatisko** [comment]
Thank you for the super quick help!

Your example's result will not have "url", but I figured it out.

**Comment by lahmatiy** [comment]
Yeah, `csstree.tokenTypes.Url` should be instead of `TYPE.Url`.

**Comment by pmatisko** [comment]
Best github support ever! Thank you! :)
