### ISSUE TITLE
Generate Flow typings out of CSS data

### ISSUE THREAD

**Issue by andreypopp** [csstree/csstree#18]
Hi, CSSTree looks nice and I want to use to generate & publish Flow typings for CSS data.

I found https://github.com/csstree/csstree/blob/master/data/mozilla-cssdata.json but it seems it `syntax` field uses BNF-like notation instead of being more structured and represented in JSON. Of course I can parse it myself but probably you can point me in the right direction of how you use it to generate parser / validator?

Sorry if I've abused GH issues—just wanted to start a discussion.

**Comment by lahmatiy** [comment]
@andreypopp If I'm correct you want to get AST of syntax. In this case, you can use csstree syntax parser to reach your goals.

```
var parseSyntax = require('csstree').syntax.parse;
var ast = parseSyntax('a | b');

console.log(ast);
// { type: 'Sequence',
//   terms:
//    [ { type: 'Keyword',
//        name: 'a',
//        sequence: null,
//        comma: false,
//        min: 1,
//        max: 1,
//        value: 'a' },
//      { type: 'Keyword',
//        name: 'b',
//        sequence: null,
//        comma: false,
//        min: 1,
//        max: 1,
//        value: 'b' } ],
//   combinator: '|',
//   value: 'a | b' }
```

Also you should use `data/index.js` instead of `data/mozilla-cssdata.json`, since it returns all mozilla's data with extensions and fixes.
One thing you should aware of is AST format may to be changed later. So pin `csstree` version until it out of alpha.

**Comment by andreypopp** [comment]
Ok, thanks, looks like I can use it.

I'll close this issue as it's not related to csstree directly. Can I use it though if I have more questions about usage of cssdata metadata?

**Comment by andreypopp** [comment]
This is epic: https://gist.github.com/fbe111c2dff16b2e5e69b154ef19e213

**Comment by lahmatiy** [comment]
> Can I use it though if I have more questions about usage of cssdata metadata?

Sure. You also can use [gitter](https://gitter.im/csstree/csstree) or write me directly ;)
