### ISSUE TITLE
A flaw in the documentation

### ISSUE THREAD

**Issue by dartess** [csstree/csstree#187]
https://github.com/csstree/csstree/blob/master/docs/traversal.md

You mention the `validateStructure` method. Now he is not exist. Perhaps you mean the `validate` method?

**Comment by shellscape** [comment]
In the root REAMDE, under `Syntax matching:`, running that example will result in an error of:

```
TypeError: ast.children.first is not a function
```

It appears that `first` is now a property and not a function and that the docs are out of sync.

**Comment by lahmatiy** [comment]
You both are correct. Thank you for pointing to this outdated things:

- `validateStructure()` is now `checkStructure()`
- `first()` (as well as `last()` and `size()`) is now a getter, so parentheses are not needed
