### ISSUE TITLE
Switch from non-ASCII code point to non-ASCII ident code point

### ISSUE THREAD

**Issue by jonathantneal** [csstree/csstree#188]
In the CSS syntax, the list of allowed characters in an identifier has been [narrowed down](https://github.com/w3c/csswg-drafts/commit/f1792dd1eb8762424bcbdbf4cc65cd11f486efdd).

This is “[an arcane detail that affects approximately no one](https://twitter.com/tabatkins/status/1513994288291475463)”, but [you](https://github.com/csstree/csstree/blob/master/lib/tokenizer/char-code-definitions.js#L41-L45) may be one of the approximately no ones affected by this.

I’m also happy to make a PR to remediate this.

**Comment by lahmatiy** [comment]
Thank you for the issue, I missed that. PR is very welcome 🙏

**Comment by lahmatiy** [comment]
I attempted to apply the new range for non-ASCII characters as specified in the CSS syntax update, but some of CSSTree's tests failed, particularly those related to encoding and decoding identifier names. I tested a selector with a character outside the new range, and it still works in all major browsers (at least the evergreen ones).

For example, the following CSS:

```html
<style>
    .𝌆 { color: green; }
</style>

<div class="𝌆">test</div>
```

Additionally, `CSS.escape('𝌆')` returns `'𝌆'`, indicating no need for escaping. However, according to the new specification, authors are required to escape such characters for them to be parsed correctly.

In this case, adhering strictly to the new spec is not straightforward, as many browsers will continue to support the broader range of non-ASCII characters defined in previous versions of the spec. CSSTree aims to be spec-compliant unless there is widespread browser support for non-standard behavior. Therefore, this issue won't be fixed at this time. I will add a comment referencing this issue to the code.

**Comment by romainmenke** [comment]
I don't think that is entirely correct.

```
'𝌆'.codePointAt(0).toString(16) // 1d306
```

This matches the catch-all at the end:

> greater than or equal to U+10000

-----

But yeah, entirely possible that browsers haven't caught up and I agree with matching the current reality.
