### ISSUE TITLE
Error using Webpack 5.x - You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

### ISSUE THREAD

**Issue by MarkusLanger** [csstree/csstree#189]
I use css-tree in my Microsoft SPFx Projects. In the old versions of SPFx, css-tree worked without problems.

In the new version SPFx 1.15 I get an error from Webpack. Now version 5.73.0 is used. Previously it was version 4.44.2.

```
[17:28:36] Error - [webpack] 'dist':
./node_modules/css-tree/lib/index.js 8:9
Module parse failed: Unexpected token (8:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| export { Lexer } from './lexer/Lexer.js';
| export { tokenTypes, tokenNames, TokenStream } from './tokenizer/index.js';
> export * as definitionSyntax from './definition-syntax/index.js';
| export { clone } from './utils/clone.js';
| export * from './utils/names.js';
 @ ./lib/webparts/helloWorld/components/HelloWorld.js 17:0-36 25:18-31 27:8-20 33:20-36
 @ ./lib/webparts/helloWorld/HelloWorldWebPart.js

```
![image](https://user-images.githubusercontent.com/12131918/176477569-4e9b9ae1-e80e-4683-8762-7add5bf65ecb.png)

Steps to reproduction
- clone repo https://github.com/MarkusLanger/css-tree-webpack-5
- npm install
- npm run package:prod

**Comment by lahmatiy** [comment]
Looks like a parser used by webpack setup doesn't support for `export * as ns` syntax. The issue was [fixed](https://github.com/webpack/webpack/issues/10460) in beta versions of webpack 5, so I'm surprised why you get such an error.

**Comment by MarkusLanger** [comment]
Thanks for the information. Then I have to check the webpack configuration.
