### ISSUE TITLE
Support range units in Value Definition Syntax

### ISSUE THREAD

**Issue by tidoust** [csstree/csstree#192]
Units are being added to [numeric ranges](https://www.w3.org/TR/css-values/#numeric-ranges) in some CSS specs to clarify how numbers need to be interpreted. Two examples:

1. `<time [0s,∞]>#` for the value of [`animation-duration`](https://drafts.csswg.org/css-animations/#animation-duration)
2. `<angle [-90deg,90deg]>` in the value of [`font-style`](https://drafts.csswg.org/css-fonts-4/#font-style-prop) 

The Value Definition Syntax parser throws an error on these values because it does not expect units to appear.

**Comment by lahmatiy** [comment]
Thank you for the issue! That's interesting, I missed that.

It's not too hard to extend DS parser, but it also affects syntax matching. And last one looks pretty huge, because this change in Range Definition Notation involves unit conversion on syntax matching. Need to think about it.
