### ISSUE TITLE
Overall Package Size

### ISSUE THREAD

**Issue by shellscape** [csstree/csstree#193]
Howdy. First off, wonderful work on this package. 

I'd like to broach the topic of the size of the package. I'm not one of those folks obsessed with package size, but when I see an opportunity to possibly reduce it significantly, I like to bring it up. The `mdn-data` package accounts for 578kb of installation size for this package, and the reason that this package is up over 1mb. Again, that's not a huge deal in the broadband era, and probably not a big deal for a package that's likely only used in a dev environment. However, it got me wondering; is the entire mdn-data package needed? Would it be possible to pull into the repo only what's needed, or use a tool like Rollup to shake out what isn't needed? I'm going to import `csstree` into `postcss-values-parser` as the tokenizer here is far superior, and I noticed that my package's size would increase as a result, that's my only motivation.

Just spitballing here. Please let me know what you think.

**Comment by lahmatiy** [comment]
@shellscape `mdn-data` is not responsible for install size of `css-tree`. This package is dual package, so it contains ESM & CJS version of modules - that's about ~50% of package's install size (when unpacked). The rest going to `dist` folder which contains bundled version of the lib (ESM & IIFE versions) as well as packed dictionary of syntax definitions (ESM & CJS version) which allow to build your own bundle using your bundler.

**Comment by shellscape** [comment]
Man, that's a huge oversight on my part. Sorry about that.
