### ISSUE TITLE
Parsing value definition syntax using stacked multipliers

### ISSUE THREAD

**Issue by pyoor** [csstree/csstree#199]
I thought this issue had been discussed in the past but I wasn't able to find anything in the tracker.  

I recently came across the [cursor](https://drafts.csswg.org/css-ui/#cursor) property.  Part of the value syntax lists `[ [ <url> | <url-set> ] [<x> <y>]? ]#?`.  It appears that css-tree is unable to handle the stacked multipliers `#?`.  At first glance it seems like this is an error in the spec, but [css-values-4](https://www.w3.org/TR/css-values-4/#component-multipliers) states:

_The + and # multipliers may be stacked as +#; similarly, the # and ? multipliers may be stacked as #?. These stacks each represent the later multiplier applied to the result of the earlier multiplier. (These same stacks can be represented using grouping, but in complex grammars this can push the number of brackets beyond readability.)_

**Comment by lahmatiy** [comment]
Thank you for pointing at this paragraph. That's an addition in level 4 that was missing before.
