### ISSUE TITLE
-apple-system is missing for font-family property

### ISSUE THREAD

**Issue by andreypopp** [csstree/csstree#20]
See https://webkit.org/blog/3709/using-the-system-font-in-web-content/

**Comment by andreypopp** [comment]
Ok, I see `font-family` isn't specified at all as for now.

**Comment by andreypopp** [comment]
Ok, reopening because I think it is worth describing constants like `monospace`, `serif`, `sans-serif` and `system` along with some prefixed ones like `-apple-system`. What do you think?

**Comment by lahmatiy** [comment]
@andreypopp You are talking about `<generic-family>`. All keywords except `system` are defined, see [`font-family` syntax](https://csstree.github.io/docs/syntax.html#properties:font-family).
I'm not sure about adding `-apple-system` (unprefixed version nobody supports so we shouldn't add it for sure). But current syntax allows using `-apple-system` w/o additions.
![image](https://cloud.githubusercontent.com/assets/270491/18707634/a851aee0-7fff-11e6-9ca1-792cc3fe2147.png)

**Comment by andreypopp** [comment]
I'm interested in having as much information about types of values as possible. Even if `-apple-system` is allows it won't show up as a suggestion if we don't describe it, for example.

Feel free to close the issue. I can fix that on my side with a set of patches if needed.

**Comment by andreypopp** [comment]
Thanks!
