### ISSUE TITLE
[TypeScript] Accessing Lexer API

### ISSUE THREAD

**Issue by TurtIeSocks** [csstree/csstree#202]
I only started using this library yesterday, so it is entirely possible that I'm accessing the API incorrectly and should instead be utilizing a different method to get the desired results, but currently csstree's type definitions do not include `lexer` as an export, despite it being available. 

Before I submit any type corrections to DefinitelyTyped, is `lexer` supposed to be accessed directly or are we "supposed" to be accessing it via a different API? 

Context:
Working on a small CMS and I want be able to access all valid CSS properties to include in an auto complete input and then have an accompanying input provide some basic validation for the CSS value. 

Thanks for the great library!

**Comment by lahmatiy** [comment]
@TurtIeSocks Yes, `lexer` is a public API, but poorly documented. I guess, that's the reason why it's not typed well. You can see sources of [csstree-validator](https://github.com/csstree/validator/blob/master/lib/validate.js) and [stylelint-validator](https://github.com/csstree/stylelint-validator/blob/master/lib/index.js) as a usage reference.

**Comment by TurtIeSocks** [comment]
Thanks for the reply and good to know! I'll work on a PR for adding `lexer` to the DefinitelyTyped repo. Okay if I tag you to look things over when I get to it?

**Comment by lahmatiy** [comment]
@TurtIeSocks Yeap, that's ok
