### ISSUE TITLE
Add support for bracketed range notation containing units

### ISSUE THREAD

**Issue by pyoor** [csstree/csstree#204]
As per https://github.com/w3c/csswg-drafts/commit/7965e6c3c54bb0a9327ccb0348eabb98ac8f0685, bracketed range notation now supports units.  

See also https://github.com/w3c/csswg-drafts/issues/7572.

**Comment by lahmatiy** [comment]
Support for dimensions in range notation was added in [v2.2.0](https://github.com/csstree/csstree/releases/tag/v2.2.0)
