### ISSUE TITLE
handling `AttributeSelector` matcher

### ISSUE THREAD

**Issue by thescientist13** [csstree/csstree#207]
Hello!

I'm a little stuck on how to handle this case where an `AttributeSelector` has a matcher property.

Given this rule
```css
pre[class*="language-"] {
  color: #ccc;
  background: none;
}
```

I would want to produce this output (basic minification).
```css
pre[class*="language-"]{color:#ccc;background:none;}
```

What I'm having trouble with is figuring how the Identifier of `class` and / or the String of `"language-"` would be aware of being in the context of an `AttributeSelector` so I would be able to accurately add the matcher in between them?  

Using [ASTExplorer](https://astexplorer.net/), I would get a tree like this
```json
{
  "type": "AttributeSelector",
  "loc": {
    "source": "<unknown>",
    "start": {
      "offset": 3,
      "line": 1,
      "column": 4
    },
    "end": {
      "offset": 23,
      "line": 1,
      "column": 24
    }
  },
  "name": {
    "type": "Identifier",
    "loc": {
      "source": "<unknown>",
      "start": {
        "offset": 4,
        "line": 1,
        "column": 5
      },
      "end": {
        "offset": 9,
        "line": 1,
        "column": 10
      }
    },
    "name": "class"
  },
  "matcher": "*=",
  "value": {
    "type": "String",
    "loc": {
      "source": "<unknown>",
      "start": {
        "offset": 11,
        "line": 1,
        "column": 12
      },
      "end": {
        "offset": 22,
        "line": 1,
        "column": 23
      }
    },
    "value": "language-"
  },
  "flags": null
}
```

If I were to log the node types of that CSS
```js
const ast = parse(/* ... */);

walk(ast, {
  enter(node) {
    console.debug(node.type);
  }
})
```

The output I would get is the following
```sh
{ type: 'StyleSheet' }
{ type: 'Rule' }
{ type: 'SelectorList' }
{ type: 'Selector' }
{ type: 'TypeSelector' }
{ type: 'AttributeSelector' }
{ type: 'Identifier' }
{ type: 'String' }
{ type: 'Block' }
{ type: 'Declaration' }
{ type: 'Value' }
{ type: 'Hash' }
{ type: 'Declaration' }
{ type: 'Value' }
{ type: 'Identifier' }
```

Since `AttributeSelector` is walked first, and that contains the value of matcher, when the `Identifier` and `String` nodes are visited, how would I know when to capture the matcher and put that value in between them to achieve this?
```css
class*="language-"
```

Thanks!

**Comment by thescientist13** [comment]
For now, implemented this as an interim solution
```js
leave: function(node, item) {
  switch (node.type) {
    ...
 
    case 'AttributeSelector':
      if (node.matcher) {
        optimizedCss = optimizedCss.replace(`${node.name.name}'${node.value.value}'`,`${node.name.name}${node.matcher}'${node.value.value}'`);
      }
      optimizedCss += ']';
      break;
  }
}
```

**Comment by lahmatiy** [comment]
Sorry, but I didn't get your question. A `given` and `want` selectors are look the same for me. If you need to change a matcher, you need to catch a `AttributeSelector` node and change `matcher` with what you need.

**Comment by lahmatiy** [comment]
I see. The walker's API is not intended for AST serialisation. You need to use `generate(ast)` method instead (see [docs](https://github.com/csstree/csstree/blob/master/docs/generate.md)). Currently it provides compact formatting only. Luckily, that's what you need.

There are several ways on how you can alter a serialisation:
- Override `generate` method of desired nodes using `fork()` method:
```js
import { fork } from 'css-tree';

const mySyntax = fork({
    node: {
        AttributeSelector: {
            generate() { ... }
        }
    }
});
```
See `lib/syntax/node` folder for examples on implementing `generate()` method.
- Using [`decorator` option](https://github.com/csstree/csstree/blob/master/docs/generate.md#decorator) for `generate()` method. Unfortunately, it's undocumented well, but you can take a look how it can be used in [source map decorator](https://github.com/csstree/csstree/blob/master/lib/generator/sourceMap.js) (you need to modify `handlers` argument to add or override a functionality).

**Comment by thescientist13** [comment]
> I see. The walker's API is not intended for AST serialisation. You need to use generate(ast) method instead (see [docs](https://github.com/csstree/csstree/blob/master/docs/generate.md)). Currently it provides compact formatting only. Luckily, that's what you need.

OH, haha.  Yes, that's pretty convenient indeed, can't believe I missed that one 😅 

> There are several ways on how you can alter a serialisation:

This is good to know because I do a little light bundling in my more complete solution, by also inlining relative `@import` paths.
```css
/* theme.css */ 
:root {
  --primary-color: red;
  --secondary-color: blue;
} 
```

```css
/* main.css */
import ./theme.css

body {
  color: var(--primary-color);
}
```

would come out as this, for example
```css
/* main.min.css */
:root {
  --primary-color: red;
  --secondary-color: blue;
}

body {
  color: var(--primary-color);
}
```

So seems like I would have a similar hook to do a tranformation like that?
```js
walk(ast, {
    enter: function (node, item) { 
      const { type, name, value } = node;

      if ((type === 'String' || type === 'Url') && this.atrulePrelude && this.atrule.name === 'import') {
        const { value } = node;

        if (value.indexOf('.') === 0) {
          const location = path.resolve(path.dirname(url), value);
          const importContents = fs.readFileSync(location, 'utf-8');

          optimizedCss += bundleCss(importContents, url);  // recursive function to keep walking all nested relative @import
        } else {
          optimizedCss += `@import url('${value}');`;
        }
   } else {
     ...
   }
}
```

Do you think that would still be feasible with `generate`?

Thanks so much for your help and for maintaining this project!  ✌️

**Comment by lahmatiy** [comment]
@thescientist13 The following question is out of scope ;) so I'm closing it.

However, answering for your question, you should alter AST and then generate a CSS. Try something like this:

```js
csstree.walk(ast, {
    enter: function (node, item, list) {
        if (node.name === 'import') {
            const location = path.resolve(path.dirname(url), value);
            const importContents = fs.readFileSync(location, 'utf-8');

            list.replace(item, csstree.List.createItem(csstree.parse(importContents)));
        }
    }
});

const newCss = csstree.generate(ast);
```
