### ISSUE TITLE
Union with `css-values` and `known-css-properties` repos

### ISSUE THREAD

**Issue by evilebottnawi** [csstree/csstree#22]
Ref to repo: https://github.com/ben-eb/css-values
Ref to repo: https://github.com/betit/known-css-properties

Why:
- I do not think that's a good idea to keep everything in the project, its code can be divided into independent modules(regards only `csstree`).
- It allow open source community to have a good package.
- I as a participant in the `stylelint` very interesting in supporting one well filled package, it will be convenient to all.
- @ben-eb and @vio currently has a little time to contribute(judging by the number commits and frequency of their), all three (and maybe more :smile: ), you do it much faster and better.

@ben-eb @vio what do you think about this? 

I would suggest creating a separate organization and hold union in her. It also would give impetus to the creation of new and stable rules for the `stylelint` and powerfull `postcss` plugins.

**Comment by ai** [comment]
I think this task is relevant https://github.com/csstree/csstree/issues/23

**Comment by evilebottnawi** [comment]
@ai this is great, but i my issue is meant to create a single package for known `at-rules`, `properties`, `pseuodu-*`, `units` and etc. I don't think it is related to `postcss` directly. Am i right?

**Comment by ai** [comment]
@evilebottnawi sure, I mean that this issues are relevant because they are both about ecosystem and compatibility with current infrastructure

**Comment by evilebottnawi** [comment]
Will wait for the reply guys, I support both ideas :+1:

**Comment by lahmatiy** [comment]
@evilebottnawi Yes, it's different suggestions. But I've understood yours only after last comment.
`css-values` is based on [Mozilla's CSSData](https://developer.mozilla.org/en-US/docs/Template:CSSData) with small fixes.
`csstree` syntax dictionary is also based on Mozilla's CSSData but with big [patch](https://github.com/csstree/csstree/blob/master/data/patch.json). And I'm going to push fixes and extensions back to Mozilla's CSSData soon.
I think Mozilla's CSSData is good start point for something common. But it should be published somewhere on github and npm. So developers can access to it and contribute more easily.
As I know @SebastianZ currently maintains Mozilla's CSSData on MDN. So I would like he or somebody else from MDN start this project. @SebastianZ, what do you think?

**Comment by evilebottnawi** [comment]
@lahmatiy 
> But it should be published somewhere on github and npm. So developers can access to it and contribute more easily.

My answer above:
> I would suggest creating a separate organization and hold union in her.

We just need everyone to come to a single point of view and start this project.
It would be interesting to answer @SebastianZ

**Comment by SebastianZ** [comment]
> I think Mozilla's CSSData is good start point for something common. But it should be published somewhere on github and npm. So developers can access to it and contribute more easily.

Coincidentally the MDN team had the same idea recently. So yes, it would be great to have the data on GitHub and npm.

Though as I am only a volunteer contributor to MDN and currently busy with [other (related) things](https://bugzilla.mozilla.org/show_bug.cgi?id=1220135), it may take some time until I can start working on porting CSSData to GitHub.
@lahmatiy if you're willing to help, we might be able to do that together.

Adding MDN people that might be interested in this discussion: @Elchi3, @teoli2003, @wbamberg

Sebastian

**Comment by evilebottnawi** [comment]
@SebastianZ I am ready to help in porting

**Comment by SebastianZ** [comment]
> @SebastianZ I am ready to help in porting

Great!

Btw. here's a related discussion:
https://groups.google.com/d/topic/mozilla.dev.mdn/PEuH7WW2Xtk/discussion

The following tasks are required:

1. Create a repo at https://github.com/mdn/. (needs to be done by MDN staff)
2. Copy the data from [CSSData](https://developer.mozilla.org/en-US/docs/Template:CSSData) to a JSON file there. (Could be done via a PR)
3. Change the macros on MDN to use the data from the GitHub repo.
4. Remove the CSSData template

The last two points are only needed for MDN, obviously, and require macro editing rights, but I'd really like to avoid having two diverging sources. And MDN welcomes any help with that. :smile:

Sebastian

**Comment by lahmatiy** [comment]
@SebastianZ Sounds good! If you have no time right now I can create a repo in csstree org. So others can start work on it and experiment with, then transfer it to MDN org. Or we need to wait until one of MDN team members creates a repo?

**Comment by evilebottnawi** [comment]
@lahmatiy lat's wait few days on answer

**Comment by Elchi3** [comment]
Hey, we are going to migrate our data JSON files to GitHub At the moment, we are discussing the repo and file organization, but once that's resolved this will live on GitHub for sure. See https://github.com/mdn/browser-compat-data/issues/25 for some of the discussion. Stay tuned!

**Comment by ben-eb** [comment]
I think moving the data from MDN to GitHub is a welcome step and hopefully encourages more contribution. css-values has a few small fixes but as I don't have edit access to the macro on MDN I can't easily contribute these changes back, so I didn't. I'm all for anything that makes it easier to contribute fixes to large public datasets, especially because I've been stung in the past with the quality of MDN's data. I, for one, would love for that to change.

Right now the idea behind css-values is to provide a first-class lint tool for stylelint; first-class in that a linter should be able to tell a user exactly how a part of CSS is invalid. [For example](https://github.com/ben-eb/css-values/blob/056a394bc9e1156e7c04fdb7575ce713b2ec6d7c/packages/css-values/index.js#L703-L717):

```js
function isIdSelector(_ref2) {
    var type = _ref2.type;
    var value = _ref2.value;

    if (type !== 'word') {
        return false;
    }
    if (value[0] !== '#') {
        return invalidMessage('Expected "' + value + '" to start with a "#".');
    }
    if (value[0] === '#' && !isCustomIdent({ type: 'word', value: value.slice(1) })) {
        return invalidMessage('Expected "' + value + '" to be a valid custom identifier.');
    }
    return true;
}
```

The main difference between css-values & csstree is that csstree parses the data from MDN on-demand in order to validate a CSS string, whereas css-values converts this data into a module that validates a property/value pair (but no data is parsed on-demand). The two approaches are quite different, and I'm not really sure how you would like to unify them. I'd welcome any suggestions. 😄

By the way [I started a little project](https://github.com/ben-eb/css-values/pull/19) with a richer dataset than known-css-properties, being based on MDN.

**Comment by lahmatiy** [comment]
> csstree parses the data from MDN on-demand in order to validate a CSS string

Yep, CSSTree parses value syntaxes on-demand and validates a property/value pair, where value is an AST node not a string.

**Comment by evilebottnawi** [comment]
@SebastianZ The guys from MDN are silent, whether it is possible as that animate them? :smile:

**Comment by Elchi3** [comment]
Hey, sorry for the delay, documenting the Web over on MDN is a lot of work for itself ;-) We've created https://github.com/mdn/data now! The former CSSData macro has been split into logical JSON files: https://github.com/mdn/data/tree/master/css 

Your contributions to this repository are very much welcome! :) We can also discuss further steps in issues there.

**Comment by evilebottnawi** [comment]
@Elchi3 great! @ben-eb @lahmatiy need review and suggestion

**Comment by SebastianZ** [comment]
> @SebastianZ The guys from MDN are silent, whether it is possible as that animate them? 😄

Sorry for being that silent myself! I totally missed your comment.

@Elchi3 thank you for pushing this project forward! Now it's way easier to contribute to the data, so hopefully there's be a lot of them in the future! 😄 

Sebastian
