### ISSUE TITLE
Patch entries scroll-timeline-axis and scroll-timeline-name are properties, not types

### ISSUE THREAD

**Issue by pyoor** [csstree/csstree#221]
Maybe I'm not fully understanding the purpose of these patch entries, but  `scroll-timeline-axis` and `scroll-timeline-name` are properties, not types.  I don't see mdn/data referencing either of these so I'm not sure exactly why they are included in the patch.  If you're just adding entries that are missing, you may as well include `scroll-timeline` as well.
https://github.com/csstree/csstree/blob/593bf37cedfbc052ad0890a6ee851510034ad437/data/patch.json#L654-L664

**Comment by pyoor** [comment]
These should probably be removed once that PR lands.

**Comment by lahmatiy** [comment]
Fixed:
- Removed `scroll-timeline-axis` from the patch since matched to `mdn-data`
- Kept `scroll-timeline-name` as the latest draft specifies it as `[ none | <custom-ident> ]#` instead of `none | <custom-ident>#` according to `mdn-data`
