### ISSUE TITLE
Find matching html element

### ISSUE THREAD

**Issue by jogibear9988** [csstree/csstree#231]
Hello,

we are workin on a html designer: https://github.com/node-projects/web-component-designer
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/364896/210664901-1fa55005-6665-463d-a9de-d25bf8b33243.png">

Now we want to introduce support of modifying a css stylesheet instead of inline styles. For this this seems to be the best css parser.

But know we thought, is there a build in way, to find wich rule matches a specific html element?

At first I thought of using element.matches (https://developer.mozilla.org/en-US/docs/Web/API/Element/matches?retiredLocale=de), but this will not work, if the selector is inside of @-rules. ( I need to know wich @rule is correct)
And also I need to get the specifity of the selector to find out wich one would the browser resolve.

Are there helper functions for this in this project?

**Comment by jogibear9988** [comment]
I found that specifity is already a feature request: https://github.com/csstree/csstree/issues/158

**Comment by lahmatiy** [comment]
A selector matching to a HTML element is out of scope of the library. To perform such kind of matching a DOM tree of entire page is needed, and even you have it it's very complicated problem. But anyway, CSSTree is working with CSS source only. 

Some years ago there was `getMatchedCSSRules()` method in Blink (Chrome), but it was [removed](https://bugs.chromium.org/p/chromium/issues/detail?id=437569&desc=2) in Chrome 64. I don't know of any similar API currently in existence.

To compute specificity you can use [@bramus/specificity](https://github.com/bramus/specificity) library, which is based on CSSTree's selector parser.

**Comment by jogibear9988** [comment]
I know there is a browser API to find the matching elment. But I thought it maybe should be a part of this, cause the browser api is only for an element. I now also found there are also APIs to resolve the "@support" queries and also there is a a API for the "@media" queries. 
So I need to Parse the stylesheet, need to look wich media and/or support queries are valid at the moment, and then I can use the Rules inside of them and check against my element.

For this I've on question. Is it possible that the parsed CSS Object Model could have a Property wich still contains the selector as a string (also in case of a media query or support query)? Cause I need it for the browser APIs to check against.

**Comment by jogibear9988** [comment]
we solved it now like this:
https://github.com/node-projects/web-component-designer/blob/master/src/elements/services/stylesheetService/CssTreeStylesheetService.ts#L147

thanks for the help
