### ISSUE TITLE
NPM Package huge, remove some folders

### ISSUE THREAD

**Issue by jogibear9988** [csstree/csstree#232]
Is there a reason why the folders:

build, demo & test are in the npm package?

**Comment by lahmatiy** [comment]
I suppose you're looking on another package, since CSSTree has no such folders. This package is [css-tree](https://www.npmjs.com/package/css-tree) on npm.

**Comment by jogibear9988** [comment]
I looked at csstree... old version... maybe someone can deprecate this... sorry
