### ISSUE TITLE
Using csstree inside of browser

### ISSUE THREAD

**Issue by jogibear9988** [csstree/csstree#233]
Hello, we try to use csstree inside of browser as esm module.

This does not work at the moment cause of 2 things:

1.) createRequire/require calls, see:
<img width="1589" alt="image" src="https://user-images.githubusercontent.com/364896/210756822-88802077-8698-4f35-a53b-d9a2049b3194.png">
<img width="1589" alt="image" src="https://user-images.githubusercontent.com/364896/210756874-bb82b4e5-4e24-4d93-b49f-3de4dc9e5ffa.png">

2.) cause of source map support:
<img width="1723" alt="image" src="https://user-images.githubusercontent.com/364896/210756974-f8a4f062-e525-4799-8bed-5fc0ba2e2db6.png">

we fixed the first in a hacky way, and the 2nd by commenting out.

But we want this fixed in the library, any ideas of a best way to fix it here?

- What would be a preferable option for importing css?
- How could we make source map support optional (we don't need it)?

We would work on a pull request for this, if we have a solution wich would be merged.

**Comment by jogibear9988** [comment]
we use importmaps

**Comment by lahmatiy** [comment]
I don't understand what is the problem with import maps? To use the library in a browser you should specify a bundle from `dist` folder, the same way as for `import` or `<script>`.

**Comment by jogibear9988** [comment]
:-D we will check, if it works I'll close.

I thought I could use imports statements during development, but these will point directly to the files in "lib", so I could not use them, but we will get it to work.

**Comment by jogibear9988** [comment]
works flawlessly... thanks
