### ISSUE TITLE
The `speak` property definition is different from the W3 standard.

### ISSUE THREAD

**Issue by rickygao** [csstree/csstree#241]
In [patch.json](https://github.com/csstree/csstree/blob/bdb6594810c3f47453d2d34fe909984a98b8e00e/data/patch.json#L381), `"syntax": "auto | none | normal"` is different from the W3 standard, which gives `auto | never | always`.

See [W3 Speech Module](https://www.w3.org/TR/css-speech-1/#speak).

**Comment by rickygao** [comment]
Is this a de facto standard?

**Comment by lahmatiy** [comment]
Thank you for highlighting this. CSSTree's syntax patch was introduced in late 2016, while the specification underwent changes in 2017.

<img width="846" alt="image" src="https://github.com/csstree/csstree/assets/270491/07858894-bc0f-4740-b4d8-c0b036547a96">

For more details, see https://github.com/w3c/csswg-drafts/issues/510
