### ISSUE TITLE
Support hask mark next to curly braces in CSS grammar

### ISSUE THREAD

**Issue by tidoust** [csstree/csstree#249]
The CSS Backgrounds Level 4 spec currently defines the value of [`box-shadow-offset`](https://drafts.csswg.org/css-backgrounds-4/#propdef-box-shadow-offset) as:

```
none | <length>{2}#
```

(the latter part to mean a "comma-separated list of horizontal and vertical offset pairs")

CSSTree's `definitionSyntax` considers that to be invalid. I suppose that the problem is the use of `#` next to `{2}`. Creating a group solves the parsing issue:

```
none | [<length>{2}]#
```

The hash-mark-next-to-curly-braces construct is not explicitly accounted for in the [CSS Values spec](https://w3c.github.io/csswg-drafts/css-values-4/#component-multipliers) for now, but grouping brackets tend to be skipped in CSS specs when possible, and this construct does not seem ambiguous.

**Comment by lahmatiy** [comment]
From what I see in the W3C issue, this is no longer the case. I couldn't find any changes in the CSS Values spec that allow a `#` multiplier after `{A,B}`. Can we close the issue?

**Comment by tidoust** [comment]
Yes, the problem could perhaps appear again in the future, but all's good for now! Plus CSS Values indeed explicitly lists stacks that are allowed and does not currently talk about curly braces.
