### ISSUE TITLE
@import rule with supports() and/or layer() parsed as Raw

### ISSUE THREAD

**Issue by bartveneman** [csstree/csstree#259]
CSSTree doesn't seem to Lex/parse `layer()` and `supports()` in `@import` rules.

## Reproduction

[Repro on StackBlitz](https://stackblitz.com/edit/csstree-import-repro?file=index.js)

For each of these examples the node's prelude is type `Raw`:

```css
@import "my.css" layer;
@import "my.css" layer(test);
@import "my.css" layer supports(display: grid);
@import "my.css" layer (min-width: 768px);
@import "my.css" layer(base) supports(accent-color: green) (min-width: 768px);
```

## Validator results

I'm slightly confused because the validator does recognise even the last example with their correct token types. [Link](https://csstree.github.io/docs/syntax/#AtrulePrelude:import)

![CSSTree validator with match results for complex import rule](https://github.com/csstree/csstree/assets/1536852/7509a247-35ba-45a3-bf92-cb9b7fc3599d)

I'd be happy to contribute a fix for this, but I got stuck on trying to add new [logic to `import.js`](https://github.com/csstree/csstree/blob/612cc5f2922b2304869497d165a0cc65257f7a8b/lib/syntax/atrule/import.js), so I might need a bit of guidance.

**Comment by bartveneman** [comment]
It looks like @ngtr6788 already implemented a fork for this for Svelte over here: https://github.com/sveltejs/svelte/pull/9098/files#diff-ed2fad2b231aca18fc2b692be85898d0099355fc12ceca4bdd2990faf5159d94, although it doesn't seem merged yet.

**Comment by lahmatiy** [comment]
This was implemented and will be available in next major version soon.

> I'm slightly confused because the validator does recognise even the last example with their correct token types

The validator works on tokens, not AST.

**Comment by bartveneman** [comment]
Thanks for the clarification!

**Comment by lahmatiy** [comment]
A new version will be published this week.
