### ISSUE TITLE
Support for plus sign for numeric values

### ISSUE THREAD

**Issue by kizu** [csstree/csstree#26]
[CSS Values and Units Module 3](https://drafts.csswg.org/css-values-3/#integers) spec descibes `<integer>` and `<number>` in a way that allows plus sign at the start:

> The first digit of an integer may be immediately preceded by `-` or `+` to indicate the integer’s sign.

And it actually works: http://dabblet.com/gist/360b21da0e0175a36698aa0d79396411

So, almost anywhere the `+` is allowed, however CSStree gives a `Mismatch` validation error.

**Comment by lahmatiy** [comment]
You're right, numbers parses is incorrect in some cases:

- preceding `+` is not including to number node (so it's 2 nodes `+` and number now)
- following exponent is not attaching to number node (e.g. `1e2` or `1e-10` are processing as number with something strange after and it cause to parse error)

I'm working on it right now. But I was faced with the problems, so it takes more time than I expected.

**Comment by kizu** [comment]
🎉
