### ISSUE TITLE
Do you have plans to replace mdn-data with other packages?

### ISSUE THREAD

**Issue by Microkiller** [csstree/csstree#261]
As you can see from mdn-data Github, https://github.com/mdn/data. They are in the process of deprecating the mdn/data package in favor of [w3c/webref](https://github.com/w3c/webref).
Do you have plans to replace it with other packages?

**Comment by romainmenke** [comment]
duplicate of : https://github.com/csstree/csstree/issues/250

I had the same question :)

**Comment by lahmatiy** [comment]
Replied in #250
