### ISSUE TITLE
Value Definition Syntax parser fails on "<an+b>"

### ISSUE THREAD

**Issue by tidoust** [csstree/csstree#263]
The following code throws a SyntaxError:

```js
const { definitionSyntax } = require('css-tree');
definitionSyntax.parse('<an+b>');
```

Error is:

```
Expect `>`
  <an+b>
-----^
```

Looking at the [Value Syntax Definition](https://drafts.csswg.org/css-values/#component-types), nothing says that such a reference to a data type needs to be only composed of characters that match `[a-zA-Z0-9\-]`, as the parser seems to assume. Granted, that's been the case until now across CSS specifications...

Problem is this construct is now used to define the [`:nth` selector](https://drafts.csswg.org/css-gcpm/#selectordef-nth) in the CSS Generated Content for Paged Media Module spec in particular, where it is to be interpreted as a reference to the basic data type [`<an+b>`](https://drafts.csswg.org/css-syntax-3/#anb-production).

**Comment by lahmatiy** [comment]
The substitution of `<an+b>` with `<an-plus-b>` in `mdn/data` and CSSTree is a practical solution, eliminating the need for parsing exceptions or rule modifications for this infrequently used syntax. While adding an exception or expanding the ident character set are alternatives, adopting `<an-plus-b>` uniformly ensures parsing consistency and simplicity. However, discussable, I have no strong opinion here.
Interesting fact that the [Selectors spec](https://drafts.csswg.org/selectors/#the-nth-child-pseudo) doesn't refer to `<an+b>` production:
<img width="838" alt="image" src="https://github.com/csstree/csstree/assets/270491/398f3901-daeb-47fe-9e6f-23081bf05504">

**Comment by tidoust** [comment]
Yes, we have a workaround in place for Webref data (which gets injected into mdn/data). Now, the single source of truth is supposed to be the spec. Ideally, that source would remain usable. I raised https://github.com/w3c/csswg-drafts/issues/9473 against the definition to suggest `<an-plus-b>` as an alternative.

**Comment by lahmatiy** [comment]
@tidoust According to the issue in csswg-drafts, the `<an+b>` syntax was renamed into `<an-b>`. Can we close the issue?

**Comment by tidoust** [comment]
Yes. The syntax hasn't been renamed in the spec yet in practice but it seems fine to close the issue on your end.
