### ISSUE TITLE
Throws if the value of :lang() pseudo-class is quoted

### ISSUE THREAD

**Issue by asamuzaK** [csstree/csstree#265]
According to the spec: [The Language Pseudo-class: :lang()](https://drafts.csswg.org/selectors/#the-lang-pseudo)
> Each language range in :lang() must be a valid CSS &lt;ident&gt; or &lt;string&gt;. (Thus language ranges containing asterisks, for example, must be either correctly escaped or quoted as strings, e.g. :lang(\*-Latn) or :lang("*-Latn").)

CSSTree throws if language ranges are quoted.

``` javascript
import { parse } from 'css-tree';
const ast = parse(':lang("*-Latn")', { context: 'selectorList' });
// throws `SyntaxError: Identifier is expected`
```

It succeeds if they are escaped, e.g. `:lang(\*-Latn)`.

**Comment by lahmatiy** [comment]
@asamuzaK Thank you for the report. Fixed according to spec, will be available in next version
