### ISSUE TITLE
Support `@position-try`

### ISSUE THREAD

**Issue by yisibl** [csstree/csstree#273]
Spec: https://drafts.csswg.org/css-anchor-position-1/#fallback-rule
Chrome 125 shipped: https://chromestatus.com/feature/5124922471874560

The syntax of the [@position-try](https://drafts.csswg.org/css-anchor-position-1/#at-ruledef-position-try) rule is:

```
@position-try <dashed-ident> {
  <declaration-list>
}
```

**Comment by lahmatiy** [comment]
Fixed. Will be available in next major version.
