### ISSUE TITLE
Using css-tree with rollup (createRequire is not exported)

### ISSUE THREAD

**Issue by mildred** [csstree/csstree#278]
pagedjs is making used of css-tree, and uses rollup to generate a bundle that includes css-tree. However when css-tree started to provide ESM modules, it also uses the `import { createRequire } from "module"` but this fails with rollup because it cannot find the module "module" (which is a Node specific thing and is not available in the browser or for rollup).

Would you consider pointing the module key in package.json to a bundle that is free from createRequire ?

**Comment by lahmatiy** [comment]
Looks like your setup doesn't recognize `browser` section in `package.json`:
https://github.com/csstree/csstree/blob/v2.3.1/package.json#L75

**Comment by scripthunter7** [comment]
@mildred By default, Rollup ignores the browser field, but if you install the [`@rollup/plugin-node-resolve`](https://www.npmjs.com/package/@rollup/plugin-node-resolve) and use it as follows, it may solve your problem:

```ts
import resolve from '@rollup/plugin-node-resolve';

// ...
  plugins: [
    resolve({
      browser: true, // this makes Rollup resolve the 'browser' field in package.json
      preferBuiltins: false, // if you want to prevent Node.js built-in modules from being bundled
    }),
    // ...
// ...
```

**Comment by lahmatiy** [comment]
I'm planning to find a way to avoid relying on the browser field in future versions. However, most modern bundlers/builders support the browser field by default or with some additional setup. I believe we can close the issue for now, as this is more of a build configuration matter than a CSSTree project issue.
