### ISSUE TITLE
Support for CSS Selectors Level 4

### ISSUE THREAD

**Issue by kizu** [csstree/csstree#28]
There can be really complex selectors in [Selectors Level 4](https://drafts.csswg.org/selectors-4/). For example, this is a valid selector (and there is already support for them in latest webkits like Safari 10):

``` CSS
:not(:not(.a), :not(.b), :not(.c), .d, :not(:matches([id=lol] > *))) {
}
```

Right now csstree throws an “Unexpected input” parsing error there.

**Comment by lahmatiy** [comment]
`:matches()` and `:has()` pseudos don't support for now.
I made my todo list public (see #29) to let everyone know what's planned.
