### ISSUE TITLE
Property grammar references should drop top level multipliers

### ISSUE THREAD

**Issue by romainmenke** [csstree/csstree#281]
See: 
- https://github.com/w3c/csswg-drafts/issues/8519#issuecomment-1464829648
- https://www.w3.org/TR/css-values-4/#component-types

`view-timeline-inset` is defined as:

```
[ [ auto | <length-percentage> ]{1,2} ]#
```

And `view()` is defined as:

```
view( [ <axis> || <'view-timeline-inset'> ]? )
```

But `view()` does not allow comma separated lists of inset params.
Only a single `[ auto | <length-percentage> ]{1,2}`.

**Comment by lahmatiy** [comment]
Duplicates #102
