### ISSUE TITLE
Suggestion: use unist as AST

### ISSUE THREAD

**Issue by justbyitself** [csstree/csstree#288]
I'm a CSSTree newbie. I think it would be nice if CSSTree could create ASTs following [unist](https://github.com/syntax-tree/unist) specification. This way CSSTree could use a lot of plugins or tools that are available. Please, tell me if this has any sense for you.

Thank you for CSSTree, it's great.

**Comment by lahmatiy** [comment]
There are no plans to change the AST format in the near future. However, CSSTree's AST can be converted into other formats (e.g., [csstree->postcss conversion](https://github.com/lahmatiy/postcss-csso/blob/master/lib/cssoToPostcss.js)), including unist. Developing such a conversion is outside the scope of the CSSTree project itself.
