### ISSUE TITLE
error:  tar: ./.output/server/node_modules/svgo/node_modules/css-tree: Cannot open: File exists

### ISSUE THREAD

**Issue by bbhxwl** [csstree/csstree#290]
I encountered this error while automatically publishing on the server, and I don't know what the reason is.

<img width="822" alt="image" src="https://github.com/user-attachments/assets/161fad8f-8a38-4cf2-9398-12710d04404d">

**Comment by lahmatiy** [comment]
The issue is related to the tar file itself and its extraction to a destination on the server. It's not related to CSSTree. You may need to ensure the target directory is clean before extracting or adjust the tar extraction options to handle existing files.
