### ISSUE TITLE
False warnings for `stroke-opacity`

### ISSUE THREAD

**Issue by ryo-manba** [csstree/csstree#299]
`stroke-opacity` generates false warnings due to [incorrect syntax](https://github.com/csstree/csstree/blob/9224418bf35dcb48146579c39ec5461b694c7af5/data/patch.json#L448), as it doesn’t handle percentages.
See: https://github.com/stylelint/stylelint/issues/8080#issuecomment-2436085151

Version 2.11 of [mdn-data](https://www.npmjs.com/package/mdn-data) has updated definitions for stroke-related properties (see https://github.com/mdn/data/pull/757).
Updating mdn-data and removing the corresponding patch should fix this issue.
https://github.com/csstree/csstree/blob/9224418bf35dcb48146579c39ec5461b694c7af5/data/patch.json#L401-L456

**Comment by lahmatiy** [comment]
The fix in `mdn/data` is incorrect: the [spec](https://drafts.fxtf.org/fill-stroke-3/#stroke-opacity) defines `<'stroke-opacity'>` as `<'opacity'>` (syntax of the `opacity` property) not `<opacity>` (a non-exists syntax definition). I changed CSSTree's patch, the issue should be resolved.

**Comment by ryo-manba** [comment]
I created a PR in `mdn/data`.
- https://github.com/mdn/data/pull/778
