### ISSUE TITLE
Bug with `center left` value for background/background-position.

### ISSUE THREAD

**Issue by kizu** [csstree/csstree#3]
![image](https://cloud.githubusercontent.com/assets/177485/18455139/d770ea2a-7950-11e6-808b-d47a5ad98d29.png)

`center left` should be valid as stated in the Note at [Spec](https://drafts.csswg.org/css-backgrounds-3/#background-position):

> Note that a pair of keywords can be reordered while a combination of keyword and length or percentage cannot. So ‘center left’ is valid while ‘50% left’ is not.

**Comment by sashasushko** [comment]
Also error if background-position `center Npx left Npx`

**Comment by lahmatiy** [comment]
@sashasushko `center Npx` is not valid, only `top`/`bottom` can used in this case.
