### ISSUE TITLE
Value Definition Syntax parser fails on `;?`

### ISSUE THREAD

**Issue by tidoust** [csstree/csstree#303]
The [`if()` notation](https://drafts.csswg.org/css-values-5/#if-notation) introduced in css-values-5, is defined with a syntax that includes `;?` to mean "an optional `;` character". The value definition syntax parser fails on that construct. Wrapping the character in single quotes instead. (as in `';'?`) fixes the problem, but `;` is one of the delimiters that are ["written literally"](https://www.w3.org/TR/css-values-4/#component-types), so quotes should not be needed.

The syntax used in the spec throws an exception:

```js
import { definitionSyntax } from "css-tree";
definitionSyntax.parse(";?");
```

This would work but is not the syntax used in the spec:

```js
import { definitionSyntax } from "css-tree";
definitionSyntax.parse("';?'");
```

**Comment by lahmatiy** [comment]
The root cause is that currently a token cannot be followed by a multiplier, but a string can.
