### ISSUE TITLE
Value Definition Syntax: Boolean Expression Multiplier renamed to `<boolean-expr[]>`

### ISSUE THREAD

**Issue by tidoust** [csstree/csstree#307]
Follow-up to #304. It seems the CSS Working Group decided to rename `<boolean[]>` into `<boolean-expr[]>`, see: https://drafts.csswg.org/css-values-5/#boolean

**Comment by tidoust** [comment]
> I knew it would be renamed, so I postponed releasing it :)

Smart move ;)
Thanks for the update!

**Comment by lahmatiy** [comment]
Available in `3.1.0`
