### ISSUE TITLE
Support additional pseudo-elements with arguments?

### ISSUE THREAD

**Issue by philschatz** [csstree/csstree#33]
There are drafts for CSS extensions that use arguments to pseudo-element selectors (ie `::slotted(.foo)` or `::before(2)`) to allow additional information.

Rather than something like hardcoding [lib/parser/type/PseudoElement.js#L20](https://github.com/csstree/csstree/blob/master/lib/parser/type/PseudoElement.js#L19-L20) what if:

1. the parser allowed any pseudo-element to have optional arguments (instead of special-casing `::slotted(.foo)`? _or_
2. the `css-tree` constructor took an additional configuration option containing all the valid pseudoelements and whether arguments were forbidden, allowed, or required?

Thanks again for all the parsing work!

**Comment by lahmatiy** [comment]
Yep, I thought about it, but had no any use case. I don't see any reason for any pseudo-element to be a functional-pseudo. Even it's not a standard yet ;)
I working on pseudos right now. So I'm going to do first point ;)

> the css-tree constructor took an additional configuration option containing all the valid pseudoelements and whether arguments were forbidden, allowed, or required?

Yes, I believe it will be available later by setting custom consumer for pseudos, functions and at-rules. It's not ready yet, but it's likely to appear in future releases.

**Comment by lahmatiy** [comment]
Available in [1.0.0-alpha4](https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha14)
