### ISSUE TITLE
Implement at-rule validation

### ISSUE THREAD

**Issue by lahmatiy** [csstree/csstree#35]
Lexer should be able to validate at-rules

- [x] `@charset`
- [x] `@import`
- [x] `@namespace`
- [x] `@media`
- [x] `@supports`
- [x] `@document`
- [x] `@page`
- [x] `@font-face`
- [x] `@keyframes`
- [x] `@viewport`
- [x] `@counter-style`
- [x] `@font-feature-values`

**Comment by Zirro** [comment]
I am not sure how close you wish to adhere to the specification with the default syntax, but it is worth noting that in the current [CSS Syntax draft](https://drafts.csswg.org/css-syntax/#charset-rule), `@charset` is no longer recognised as a rule. The first occurrence is even dropped at the parsing stage.

**Comment by lahmatiy** [comment]
@Zirro Yep, that's correct for runtime, not for source processing

**Comment by lahmatiy** [comment]
Starting [`v1.1.0`](https://github.com/csstree/csstree/releases/tag/v1.1.0) the validation of at-rules is supported.
