### ISSUE TITLE
Typo (List exception string)

### ISSUE THREAD

**Issue by strarsis** [csstree/csstree#42]
Is this a typo?
````
[...]doesn\'t below to list[...]
````
Shouldn't this be "belong" instead?

**Comment by lahmatiy** [comment]
Yep, it's a typo. Would you like send a PR?

**Comment by strarsis** [comment]
Sure! https://github.com/csstree/csstree/pull/43

**Comment by lahmatiy** [comment]
Thank you for contribution!
