### ISSUE TITLE
Add tolerance

### ISSUE THREAD

**Issue by strarsis** [csstree/csstree#45]
Related to issue: https://github.com/csstree/csstree/issues/16

One svgo test deliberately uses incorrect inline style declarations, css-tree currently aborts parsing it:
```js
'use strict';
var csstree = require('css-tree');
var ast = csstree.parse("fill:#000; c\olor: #fff; /**/illegal-'declaration/*'; -webkit-blah: 123  ; -webkit-trolo: 'lolo'; illegal2*/");
````

````
[...]node_modules/css-tree/lib/tokenizer/Tokenizer.js:389
        throw new CssSyntaxError(
        ^

CssSyntaxError: Identifier is expected
    at new CssSyntaxError ([...]node_modules/css-tree/lib/tokenizer/error.js:54:17)
[...]
````

A tolerance mode would be great also for parsing stylesheet context styles.
It can help coping with broken/strange/exotic styles.

**Comment by lahmatiy** [comment]
It's better to expect parsing can fail and wrap `parse()` into `try`/`catch`. I believe tolerance mode will be implemented one day. But that's really complicated feature and AST will have something unparsed, that should be handled somehow.
Anyway, I don't think we need a duplicate issue. Let's close it?

**Comment by lahmatiy** [comment]
`v1.0.0-alpha.26` is out and now parser is tolerant to errors by default.
Read more in [release notes](https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha.26)
