### ISSUE TITLE
Support for font-display

### ISSUE THREAD

**Issue by acupofspirt** [csstree/csstree#48]
I am use CSSTree as a plugin for Gulp. And when I trying to use _font-display_ property it fails with 'unknown property' error. Can you add support for that property?
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) 
[Spec](http://tabatkins.github.io/specs/css-font-display)

**Comment by pepelsbey** [comment]
Yes please, `font-display` is quite common these days and this golden dot makes me want to disable this plugin again :(

![image](https://user-images.githubusercontent.com/105274/36449929-62f001fe-169d-11e8-8b3a-9c6ba6dafdd8.png)

**Comment by acupofspirt** [comment]
It seems that the font-display property has long existed in mdn dictionaries: https://github.com/mdn/data/blob/master/css/at-rules.json#L131
@lahmatiy how can I help you to solve this issue? What's the trouble?

**Comment by lahmatiy** [comment]
It will be supported when CSSTree gets ability to check at-rule descriptors. Some other descriptors works fine by incident – they have similar syntax as declarations with the same name, but these are all different things.

**Comment by lahmatiy** [comment]
That's not an issue anymore. Since CSSTree validate at-rules in a different way starting from 1.1.0, using at-rule definitions.
Latest version of VS Code plugin should work fine.
