### ISSUE TITLE
Some SVG properties are not recognized

### ISSUE THREAD

**Issue by kizu** [csstree/csstree#5]
Not sure if they should be, but some of the properties (`clip-rule`, maybe some others) are not recognized by csstree.

**Comment by lahmatiy** [comment]
Yes, some of them are known (search by `svg` in [data/patch.json](https://github.com/csstree/csstree/blob/master/data/patch.json)). I didn't try to reach 100% of them, so some may be missed.
Would be great if you point what's missed.

**Comment by lahmatiy** [comment]
Properties added:
- alignment-baseline
- baseline-shift
- clip-rule
- dominant-baseline
- fill-opacity
- glyph-orientation-horizontal
- glyph-orientation-vertical
- kerning
- letter-spacing
- shape-rendering

Fixed:
- image-rendering (keywords added)
- writing-mode (extended with SVG specific keywords)

**Comment by Mouvedia** [comment]
@lahmatiy `d` is missing.
e.g. `d: none;`
ref https://www.w3.org/TR/SVG2/paths.html#TheDProperty

**Comment by lahmatiy** [comment]
@Mouvedia The `d` property was added in CSSTree v3.0.0

PS That's a closed issue. Please, open a new one or propose a PR next time, otherwise a report/comment can be missed
