### ISSUE TITLE
[alpha20/22] Missing declaration name in declaration in media query

### ISSUE THREAD

**Issue by strarsis** [csstree/csstree#55]
After updating css-tree to latest alpha (20/22), 
declaration name in declaration in media query is missing in ([svgo/inlineStyles plugin](https://github.com/svg/svgo/pull/592)) tests, 
see this pared-down test case: https://github.com/strarsis/svgo/tree/test-css-tree-alpha20

````
$ git clone https://github.com/strarsis/svgo
$ cd svgo
$ git checkout test-css-tree-alpha20
$ yarn install
$ npm test
````
Downgrading to older alpha (1.0.0-alpha18) resolves this issue, 
see the working branch: https://github.com/strarsis/svgo/tree/inlineStyles.

Related issue?: https://github.com/csstree/csstree/issues/39

**Comment by lahmatiy** [comment]
In your branch `inlineStyles` plugin does nothing https://github.com/strarsis/svgo/blob/test-css-tree-alpha20/plugins/inlineStyles.js

**Comment by strarsis** [comment]
@lahmatiy: Correct, the issue occurs by just installing css-tree recent alphas, apparently they also interfere with svgo internals.

**Comment by lahmatiy** [comment]
@strarsis Since alpha20 `Atrule.expression` is always contain a `AtruleExpression`, so `MediaQueryList` lays one level deeper now. You need change [line](https://github.com/strarsis/svgo/blob/165fec488b1412038d7b8413f0e28baee01e4341/lib/css-tools.js#L66
):
```js
        if (selector.atrule.expression.type === 'MediaQueryList') {
```
to 
```js
        if (selector.atrule.expression &&
            selector.atrule.expression.children.first().type === 'MediaQueryList') {
```
This fixed problem on my side.

**Comment by strarsis** [comment]
@lahmatiy: Thanks! For whatever reason this also influenced svgo without the plugin.
