### ISSUE TITLE
SemVer releases

### ISSUE THREAD

**Issue by peterbe** [csstree/csstree#59]
I don't know how it happened but even thought I have `^1.0.0-alpha23` in my `package.json` after running `yarn install` (aka `yarn`) I now I have version `1.0.0-alpha9` installed. 
Not sure how that happened. But `1.0.0-alpha9` >= `1.0.0-alpha23`. Wouldn't have happened if it had been called `1.0.0-alpha09`. 

<img width="973" alt="screen shot 2017-09-11 at 10 02 02 am" src="https://user-images.githubusercontent.com/26739/30278405-4984f764-96d8-11e7-8338-30b0760eee6b.png">

Wouldn't happen if it was a patch number instead:

<img width="981" alt="screen shot 2017-09-11 at 10 02 37 am" src="https://user-images.githubusercontent.com/26739/30278468-6c235ab8-96d8-11e7-8968-adb5fcdc0a32.png">

**Comment by peterbe** [comment]
The way I now prevent this from happening is pinning exactly `1.0.0-alpha23` in my `package.json` but I don't know if I like that since it can cause trouble for people installing my app amongst a bunch of other apps.

**Comment by smelukov** [comment]
@peterbe Hello. Please pin a version for now. https://github.com/yarnpkg/yarn/issues/3560
We'll fix it in the future

**Comment by lahmatiy** [comment]
@peterbe As suggested in yarnpkg/yarn#3560 we need to add a period before alpha version (i.e. `1.0.0-alpha.23`) to make semver works properly. And we will do this when CSSTree's API and AST become stable. Version pinning is a right decision at the moment, since any new version may break everything.

**Comment by lahmatiy** [comment]
With [`v1.0.0-alpha.26`](https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha.26) there is a period in version. So since this version ranges should work as expected.
Nevertheless, I highly recommend don't use ranges and pin a version in your package.json until CSSTree is in alpha stage.
