### ISSUE TITLE
Lengths can be sometimes without pixels

### ISSUE THREAD

**Issue by kizu** [csstree/csstree#6]
[SVG spec](https://www.w3.org/TR/SVG11/coords.html#Units) says that

> One px unit is defined to be equal to one user unit. Thus, a length of "5px" is the same as a length of "5".

So, for example, `stroke-width: 2;` should be valid.

Maybe the <length> could be parsed differently in different contexts (regular css/svg properties)?

**Comment by lahmatiy** [comment]
Yes, it's true for SVG properties only. I guess we should extend syntax of those properties `<percentage> | <length>` -> `<percentage> | <length> | <number>`.
All we need is change `data/patch.json`. PR is welcome ;)
