### ISSUE TITLE
Add `async` to dependencies

### ISSUE THREAD

**Issue by sideshowbarker** [csstree/csstree#65]
If you try to install the `csstree` npm package without `async` installed, you’ll get an error:

     Error: Cannot find module 'async'

**Comment by lahmatiy** [comment]
Make sure you install `csstree` as `npm install css-tree` (i.e. it should be `css-tree`). `csstree` on npm is another package at the moment and it have a problem with install.

**Comment by sideshowbarker** [comment]
ah ok — thanks (closing this)
