### ISSUE TITLE
Best way of pruning rules (children)

### ISSUE THREAD

**Issue by pocketjoso** [csstree/csstree#69]
Hi,
I just came across this CSS Parser and it looks great. I would like to try using it in [penthouse](https://github.com/pocketjoso/penthouse/) for critical css generation (via pruning an existing stylesheet). Currently Penthouse uses [rework css parser](https://github.com/reworkcss/css) but it is neither fault tolerant nor maintained, so I've been looking for a replacement for a while now.

So back to csstree. I realise this is most likely not a use case you have had, but what are your thoughts on how to (make it possible to) prune the rules (children) in the parsed css? I'm guessing it's hard to implement anything like `Array.prototype.filter` on your custom `List` data type... How about if I could annotate rules as ~ `toBeRemoved` - could they then be scrapped by the `toString` function? Without looking deeply into your code I presume this would be the easiest way to support my use case. What are your thoughts on this? Is there a better way? Are you interested in supporting this in the library? Even if not, do my thoughts here make sense to you? I would be 💯 if this would be supported in your library but I would understand if you would want to limit the scope - if so I could possibly just fork and implement a custom to string generator..

Thanks again for the library!

**Comment by pocketjoso** [comment]
Found from/toPlainObject methods via https://github.com/csstree/csstree/issues/68 - looks like they should resolve my issue.

What's the performance overhead of calling these methods? If substantial I'm guessing I would lose the speed benefit of switching to cssTree (over rework css)..

**Comment by lahmatiy** [comment]
You need to use List#remove() method if you need to remove some node from a list:

```js
node.children.each((node, item, list) => {
    if (node.toBe === 'removed') {
        list.remove(item);
    }
})
```

> I'm guessing it's hard to implement anything like Array.prototype.filter on your custom List data type

It's not so hard. I thought about missed Array's methods like `filter`. So, it may be added in future, but we need to know when it useful.

> What's the performance overhead of calling these methods

It walks through a AST and converts List to Array or vice versa. You should not use those methods to work with AST, until you export/import a tree. Usually proper API exists to solve the problem. Just describe what you want to do and I'll try to help.

**Comment by pocketjoso** [comment]
Thanks for your quick reply.

So you're saying I could right now:
use `walkRules` and call `list.remove(item)` on the rules I want to remove. It works remove the active rule during the traversal (I guess since you said so), and afterwards I will be able to call `csstree.translate` to generate the pruned stylesheet I want?

I could not yet use your `walk`/`walkRules` methods the way I needed them ([exposed](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageexposefunctionname-puppeteerfunction) as isolated methods to the (chrome headless) browser environment I'm running this in) because the [createContext function](https://github.com/csstree/csstree/blob/master/lib/walker/create.js#L211) in the walker file is not available in the exported function scope, so [this line](https://github.com/csstree/csstree/blob/master/lib/walker/create.js#L262) crashes. I haven't understood how your code works fully yet to understand why it works when calling `walk` on the `csstree` module directly.. in either case if it's just this simple method I could patch it myself, at least to test. FYI I'm only traversing the tree in the browser. The parsing and generation is done in node.

**Comment by lahmatiy** [comment]
>  I could right now: use walkRules and call list.remove(item) on the rules I want to remove. It works remove the active rule during the traversal (I guess since you said so), and afterwards I will be able to call csstree.translate to generate the pruned stylesheet I want?

Correct. You can remove items of list on traversal through it, it's safe. `translate()` just convert a AST into a string. You can change AST as you want but respect [format](https://github.com/csstree/csstree/blob/master/docs/ast.md). If you need a copy of tree, use `clone()` method.

> I could not yet use your walk/walkRules methods the way I needed them (exposed as isolated methods to the (chrome headless) browser environment I'm running this in) because the createContext function in the walker file is not available in the exported function scope, so this line crashes. I haven't understood how your code works fully yet to understand why it works when calling walk on the csstree module directly..

Have no clue why it doesn't work, since never try pass it to headless chrome. Did you try inject csstree dist into document and use it as a library?

> FYI I'm only traversing the tree in the browser. The parsing and generation is done in node.

I understand the case. I thought to make at least walker and generator to be tolerant to arrays as children, may be in next releases. At the moment a single solution is convert List<->Array via to/fromPlainObject.

**Comment by lahmatiy** [comment]
I think we sorted out this question. Feel free to re-open the issue if asked question is still open.

**Comment by pocketjoso** [comment]
Indeed, thanks again for the help!
