### ISSUE TITLE
Using the Value Definition Syntax parser

### ISSUE THREAD

**Issue by aaronbeall** [csstree/csstree#71]
This project appears to have a parser for the [value definition syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax) which I would love to use (also against mdn/data) for a different purpose (not parsing CSS or validating values). Is it possible to use this parser by itself? I've spent a little time looking through the documentation and code and can't quite figure it out...

**Comment by lahmatiy** [comment]
@aaronbeall You should use [`csstree.grammar.*` methods](https://github.com/csstree/csstree/tree/master/lib/lexer/grammar): parse, walk and translate.

Take a look https://github.com/csstree/docs as examples of usage.

**Comment by lahmatiy** [comment]
Closing this for now. Feel free to reopen in case you have more questions.

**Comment by aaronbeall** [comment]
Thanks, sorry I never followed up but this clears it up.
