### ISSUE TITLE
-webkit-font-smoothing: auto is marked as invalid by CSS syntax validator

### ISSUE THREAD

**Issue by victor-homyakov** [csstree/csstree#75]
[CSS syntax validator](https://csstree.github.io/docs/validator.html) marks `-webkit-font-smoothing: auto` declaration as invalid

Values that are suggested in my current Chrome's DevTools (and then recognized without errors): `antialiased`, `auto`, `inherit`, `initial`, `none`, `subpixel-antialiased`, `unset`

https://csstree.github.io/docs/syntax.html#Property:-webkit-font-smoothing shows only `none | antialiased | subpixel-antialiased`

**Comment by lahmatiy** [comment]
`inherit`, `initial` and `unset` are [CSS-wide keywords](https://www.w3.org/TR/css-values-3/#common-keywords)
So we just need to add `auto`. I have no mention about it on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth). However, I confirm that `auto` is supported and moreover is the initial value (I checked Chrome and Safari).

**Comment by lahmatiy** [comment]
- Found useful article https://www.zachleat.com/web/font-smooth/
- Fixed the MDN page: https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth
- Going to fix a syntax

**Comment by lahmatiy** [comment]
Fixed, will be available in next release/update.
