### ISSUE TITLE
& gives CssSyntaxError: Selector is expected

### ISSUE THREAD

**Issue by ghost** [csstree/csstree#79]
For the following code:
```js
csstree.parse( `&.bar`, { context: 'selector' } );
```
I expect it to parse without error (with a Raw node for the &, I assume), as this is a valid scss selector.

Instead it throws an error.

**Comment by acconrad** [comment]
This is a CSS syntax parser, not an SCSS syntax parser, so this isn't supposed to work

**Comment by errorx666** [comment]
The README states:

```
The only thing the parser departs from the specification is that it doesn't throw away bad content, but wraps it in the special nodes, which allows processing it later.
```

**Comment by acconrad** [comment]
My guess is "bad content" is up for debate - if it throws an error this may not be bad content but invalid content. Since I'm not a contributor I can't comment but I would imagine this is why the error exists.

**Comment by revelt** [comment]
Strange, I can't recreate this in ASTExplorer:

![raw](https://user-images.githubusercontent.com/8344688/72533700-7c867a00-386d-11ea-8d26-a943c4b46f3a.png)

the result does return raw, at least in the GUI

**Comment by errorx666** [comment]
@revelt It may have been resolved in the 2 years since I opened this issue.

**Comment by lahmatiy** [comment]
Since [CSS Nesting](https://www.w3.org/TR/css-nesting-1/) is now on standardization path, a support for `&` selector (nesting selector) will be added in next releases as well as `@media` at-rule and rules with a prelude starting with `&` inside a block.
