### ISSUE TITLE
npm versioning "rolled back" after 1.0.0-alpha25 / 1.0.0-alpha.26

### ISSUE THREAD

**Issue by SphinxKnight** [csstree/csstree#80]
First: thanks for all those tools :)
Second: I'm pretty new to npm ecosystem and semver so please, don't hesitate to correct me.
Having installed csstree as a dependency for my own project, I installed the latest release and my `package.json` got `^1.0.0-alpha.28` which is fine :) 

However, when I install it on another computer where package.json is initialized, npm install 1.0.0-alpha9… which is a previous release.

The point is, I think, that semver states "1.0.0-alpha.X" < "1.0.0-alphaY" but the release numbers changed syntax between alpha25 and alpha.26…

This might be checked by running `npm outdated` when 1.0.0-alpha.28 is installed: "wanted" is 1.0.0-alpha9

**Comment by lahmatiy** [comment]
Yep, semver has a sorting issue when postfix label has a number with no a dot. That's why the dot was added to postfix starting with `alpha.26`.
While CSSTree is on alpha stage it's better to pin exactly version w/o `^`, `~` or like that.

**Comment by SphinxKnight** [comment]
OK for me, thanks for the answer :)
