### ISSUE TITLE
Add a bunch of Grid Layout properties

### ISSUE THREAD

**Issue by pepelsbey** [csstree/csstree#81]
1. Add named lines syntax detection

<img width="765" alt="screen shot 2018-02-23 at 10 51 03" src="https://user-images.githubusercontent.com/105274/36584906-b75ad886-188c-11e8-94b4-95df5b38293f.png">

2. Add `justify-self` and `justify-item` properties [from the spec](https://www.w3.org/TR/css-grid-1/#row-align). MDN: [`justify-self`](https://developer.mozilla.org/en-US/docs/Web/CSS/justify-self), `justify-item` is not there yet.

<img width="532" alt="screen shot 2018-02-23 at 11 24 29" src="https://user-images.githubusercontent.com/105274/36584907-b7790e0a-188c-11e8-955f-e232189aed72.png">

3. Add `gap` shorthand [from the spec](https://www.w3.org/TR/css-grid-1/#gutters), which is an alias to `[grid-gap](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-gap)` property.

<img width="358" alt="screen shot 2018-02-23 at 11 25 07" src="https://user-images.githubusercontent.com/105274/36584908-b7988ca8-188c-11e8-8c5a-6072a4943eb6.png">

**Comment by pkuczynski** [comment]
Elements of this ticket are mentioned in #50

**Comment by pepelsbey** [comment]
The problem with #50 is that there’s a list of non-standard properties found on internet. In this case all of them are part of actual spec and supported in various browsers.

**Comment by pkuczynski** [comment]
Yes, I know. Just marking this two issues as related. Point 2. is listed in the source repo https://github.com/mdn/data/issues/149. I will see if I can send them a PR :)

**Comment by pkuczynski** [comment]
mdn/data#184 and mdn/data#185 was merged so we only waiting for mdn/data#189...

**Comment by pkuczynski** [comment]
Not sure how can I add named lines syntax detection. @lahmatiy?

**Comment by lahmatiy** [comment]
@pkuczynski That's a problem of lexer's match algorithm. Added this case to the issue list and describe possible solutions (see #67)

**Comment by pkuczynski** [comment]
mdn/data#189 has been merged @lahmatiy

**Comment by pkuczynski** [comment]
Should we close this one?

**Comment by lahmatiy** [comment]
Nope, unfortunately. We need publish a CSSTree and plugins version before. Also named line issue is still here :(

**Comment by pkuczynski** [comment]
I forked named line issue to #83 for clarity, so this one can be closed.

**Comment by lahmatiy** [comment]
Good news, all issues was fixed in `1.0.0-alpha.29`. Atom & VS Code just updated.
Thank you guys!
