### ISSUE TITLE
Add named lines syntax detection

### ISSUE THREAD

**Issue by pkuczynski** [csstree/csstree#83]
<img width="765" alt="36584906-b75ad886-188c-11e8-94b4-95df5b38293f" src="https://user-images.githubusercontent.com/374864/38724648-2ec800f8-3f05-11e8-9250-716d4a77174d.png">

That's a problem of lexer's match algorithm. Possible solutions see #67

**Comment by pkuczynski** [comment]
This is a fork from #81

**Comment by lahmatiy** [comment]
Fixed in `1.0.0-alpha.29`
