### ISSUE TITLE
SCSS/SASS syntax support

### ISSUE THREAD

**Issue by smelukov** [csstree/csstree#84]
We are stared to implement SCSS-syntax support [here](https://github.com/csstree/csstree-scss-syntax)
But there are many works to do

**Comment by revelt** [comment]
That's awesome but this issue is not actionable, there are different preprocessors, like LESS — supporting all of them is outside of the scope, this is firstly a CSS parser.

I suggest we close this ticket. The SCSS syntax support is outside of the scope.

**Comment by lahmatiy** [comment]
I believe that's a subject for another library (probably based on CSSTree as a syntax extension). Closing it as won't to fix.
