### ISSUE TITLE
Add size property for @page

### ISSUE THREAD

**Issue by pepelsbey** [csstree/csstree#86]
![image](https://user-images.githubusercontent.com/105274/41490467-dbe80f16-70fc-11e8-8610-e4cb86d19f21.png)

It’s supported in Chrome and [documented on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/@page/size).

**Comment by pepelsbey** [comment]
It’s listed in #50, but consider it as a reminder. It’s not a random vendor nonsense, it’s a new trendy property everyone’s talking about.

**Comment by lahmatiy** [comment]
Thank you for the issue. MDN have no support info and also mdn/data have no a syntax description for that.
Anyway, that's the same case as #48:
> It will be supported when CSSTree gets ability to check at-rule descriptors (soon).
It's a descriptor, not a declaration. Descriptors can have different meaning and syntax depending on at-rule. So you need await a little.

**Comment by lahmatiy** [comment]
Looks like that's not an issue for a long time, CSSTree should be ok with it now.
