### ISSUE TITLE
Support iOS 11 props

### ISSUE THREAD

**Issue by smelukov** [csstree/csstree#90]
Support props and fn's that was shipped in iOS 11

* constant()
* env()
* safe-area-*

https://webkit.org/blog/7929/designing-websites-for-iphone-x/

**Comment by zaiyu91** [comment]
wow!!

Thank you for your help.

It help me to coding.

**Comment by Sureepons** [comment]
https://github.com/csstree/csstree/issues/90#issuecomment-412108059

**Comment by lahmatiy** [comment]
`env()` is supported since added to mdn/data. Others are not at the moment

**Comment by lahmatiy** [comment]
`constant()` was replaced by `env()` after iOS 11.2
`safe-area-*` is just a `<custom-indent>`
Looks like we may close the issue

**Comment by carlosjeurissen** [comment]
Seems `env()` is not supported at the moment of time. Is this intended?
