### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by mlucool** [csstree/csstree#98]
Hi,

When do you expect the next release to be? Specifically I'd like [this commit](https://github.com/csstree/csstree/commit/9c6eda0059e137fa528126bb025c537f1c3fb576).

Thanks!

**Comment by lahmatiy** [comment]
Sorry for the very long delay. There were numerous issues with syntaxes, complicated transition on new token type set and related.
New version published with mdn/data 2.0.3. More details in release notes: https://github.com/csstree/csstree/releases/tag/v1.0.0-alpha.30
